// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozkixbsjxxibzhxphflp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96a2l4YnNqeHhpYnpoeHBoZmxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTQyMTgsImV4cCI6MjA2NDUzMDIxOH0.3bJYg-9meei0edh2x5V6Q0Me7G6Y6HgQ_zDGDjXO5tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);